
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[385] =
    {   0,
        0,    0,  111,  109,  108,  107,   95,  109,    1,  101,
       94,  109,   89,   90,   99,   98,   86,   97,   93,  100,
       52,   51,   87,   83,  102,   88,  103,  106,   49,   49,
       91,   92,  104,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   84,
      105,   85,   96,   82,    0,   60,    0,   68,   85,   77,
       69,    0,    0,   66,   74,   64,   75,   65,   76,    0,
       55,    2,    3,   67,   56,   52,    0,    0,   52,   52,
        0,   52,   51,   51,   51,   51,   92,   84,   91,   73,
       79,   81,   80,   72,   49,    0,    0,   70,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   11,   49,   49,   49,   49,   49,   49,
       19,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   71,   78,   60,    0,    0,    0,    0,
       53,    0,    0,   61,    0,   55,    3,    0,   56,    0,
       54,   52,   52,   52,   52,    0,   50,   51,   51,   51,
       51,   63,   62,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   17,   49,   49,   21,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,    0,    0,    0,    0,    0,   55,
        0,   56,   54,   52,    0,    0,   50,    0,   50,   50,
       51,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,    4,   49,    6,    7,   49,   49,   49,   49,   13,
       14,   49,   49,   18,   49,   22,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   35,   49,
       49,    0,    0,    0,    0,    0,    0,   50,   50,    0,
       57,   50,   50,   49,   49,   41,   49,   49,   49,   49,
       49,   49,   49,    5,    8,   49,   49,   49,   49,   16,
       49,   49,   49,   49,   26,   49,   49,   49,   49,   49,

       49,   33,   49,   49,   37,    0,   58,    0,   59,   57,
       50,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   12,   15,   20,   49,   49,   25,   27,   28,
       29,   30,   31,   49,   49,   49,   58,   59,   49,   49,
       40,   49,   49,   49,   49,   49,   49,   49,   49,   10,
       49,   49,   32,   49,   49,   38,   39,   42,   43,   49,
       49,   49,   49,   48,    9,   23,   24,   34,   36,   49,
       45,   49,   49,   44,   49,   49,   49,   49,   49,   49,
       49,   47,   46,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[395] =
    {   0,
        0,    0,  693,  694,  694,  694,  667,   72,  694,   53,
       72,  646,  694,  694,  665,   68,  694,   69,   67,   79,
      102,   82,  663,  694,   83,  663,   84,  694,    0,  106,
      694,  694,  662,  102,  619,  621,   50,   63,   67,   30,
      622,   92,  621,  629,   91,  610,  147,  618,  623,  694,
       88,  694,  694,  694,  128,  161,  140,  694,  694,  694,
      694,  120,  152,  694,  694,  694,  694,  694,  694,  662,
      158,  694,    0,  694,  167,  211,  218,  236,  138,  137,
      661,  142,  226,  152,  155,  174,  694,  694,  694,  651,
      694,  694,  694,  650,    0,  178,  629,  694,  147,  611,

      610,  618,  610,  607,  602,  611,  612,  599,  611,  598,
      613,  600,  606,  592,  593,  590,  590,  593,  590,  587,
        0,  159,  591,  207,  589,   96,  133,  593,  586,  643,
      150,  202,  590,  694,  694,  264,  641,  255,  269,    0,
      694,  271,    0,  694,  279,  694,    0,  289,  694,  263,
      299,  198,  694,  608,  585,    0,  287,  210,  694,  606,
      583,  694,  694,  584,  578,  577,  578,  576,  587,  571,
      585,  569,  565,  569,  581,  576,  564,  230,  578,  576,
      572,  564,  570,  573,    0,  559,  563,    0,  564,  561,
      551,  549,  551,  553,  560,  546,  544,  544,  556,  546,

      550,  554,  556,  529,  316,  357,  304,  403,  319,  346,
      323,  407,  694,  694,  252,  288,  288,  378,  165,  314,
      694,  530,  524,  523,  515,  524,  520,  510,  495,  499,
      488,    0,  490,    0,    0,  481,  489,  477,  484,    0,
        0,  478,  475,    0,  479,    0,  474,  474,  473,  470,
      482,  472,  476,  481,  480,  478,  468,  471,    0,  459,
      470,  300,    0,  267,    0,  449,  458,  244,  694,  350,
      462,  483,  460,  457,  460,    0,  456,  450,  456,  442,
      450,  457,  453,    0,    0,  442,  443,  447,  437,    0,
      444,  430,  437,  432,    0,  440,  437,  439,  419,  428,

      422,    0,  413,  415,    0,  395,  468,  399,  491,  694,
      694,  298,  414,  410,  403,  398,  391,  400,  398,  401,
      380,  380,    0,    0,    0,  392,  392,    0,    0,    0,
        0,    0,    0,  388,  388,  380,  694,  694,  373,  383,
        0,  360,  378,  355,  339,  353,  347,  346,  339,    0,
      320,  316,    0,  328,  321,    0,    0,    0,    0,  308,
      302,  310,  298,    0,    0,    0,    0,    0,    0,  281,
        0,  283,  271,    0,  263,  184,  140,  132,   90,   68,
       16,    0,    0,  694,  550,  559,  563,  570,  577,  586,
      591,  593,  595,  597

    } ;

static yyconst flex_int16_t yy_def[395] =
    {   0,
      384,    1,  384,  384,  384,  384,  384,  385,  384,  384,
      384,  386,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  387,  387,
      384,  384,  384,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  384,
      384,  384,  384,  384,  385,  384,  388,  384,  384,  384,
      384,  386,  389,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  390,  384,  384,  384,  384,  384,  384,  384,
      391,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  387,  385,  386,  384,  387,  387,

      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  384,  384,  384,  384,  384,  385,  392,
      384,  386,  393,  384,  384,  384,  390,  384,  384,  384,
      384,  384,  384,  384,  384,  394,  391,  384,  384,  384,
      384,  384,  384,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  385,  385,  386,  386,  384,  384,
      384,  384,  384,  384,  394,  394,  384,  384,  384,  384,
      384,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  385,  206,  386,  208,  384,  384,  384,  384,  384,
      384,  384,  384,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,

      387,  387,  387,  387,  387,  384,  384,  384,  384,  384,
      384,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  384,  384,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
      387,  387,  387,    0,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384

    } ;

static yyconst flex_int16_t yy_nxt[771] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   30,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   29,   43,   29,
       29,   29,   29,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   56,   58,   59,   60,
       65,  383,   70,   67,   71,   71,   71,   71,  118,   88,
       72,  119,   66,   68,   69,   73,   61,   75,  110,   83,

       83,   83,   83,   74,   89,  111,   90,   91,   93,   94,
       96,  112,  134,   78,   97,  113,   57,   75,   84,   76,
       76,   77,   77,   85,  114,  115,  382,  116,  141,   99,
      100,  101,   56,   78,   78,  102,  117,  103,   79,  104,
       86,  105,  106,   80,   81,  121,  125,  126,   85,  107,
      194,   96,  122,  381,   78,   97,  127,  139,  139,  128,
       82,  135,  136,  136,   63,   96,  130,  195,   80,  142,
      142,   81,   57,  154,  152,   71,   71,   71,   71,  153,
      380,  196,   56,  153,   71,   71,   71,   71,  158,  145,
      146,  160,  379,  159,  146,  155,  197,  137,  148,  149,

      152,  272,  137,  149,  153,  164,  200,  131,  153,  140,
      145,  146,  165,  161,  201,  159,  146,  187,  159,  148,
      149,  143,   57,  273,  188,  149,   75,  138,   76,   76,
       77,   77,  158,   75,  378,   77,   77,   77,   77,  153,
      159,   75,   78,   83,   83,   83,   83,   79,  150,   78,
      150,  159,   80,  151,  151,  151,  151,   78,  202,   96,
      203,  190,   84,   78,  153,  136,  136,   85,   96,   82,
       78,  191,  192,   56,  137,  141,  159,   80,   78,  141,
      151,  151,  151,  151,   86,  269,  205,  205,  207,  207,
      266,  209,   85,  209,  236,  237,  210,  210,  210,  210,

      137,  211,  216,  211,   56,  137,  212,  212,  212,  212,
      269,   63,  141,   57,  266,   63,  151,  151,  151,  151,
       56,  264,  264,  217,  268,  218,  267,  377,  219,  269,
      138,  213,  376,  262,  262,  213,  210,  210,  210,  210,
      212,  212,  212,  212,   57,  220,  339,  375,   63,  218,
      267,  374,  213,  219,  269,  269,  373,  213,  372,  340,
       57,   56,  371,  210,  210,  210,  210,  271,  271,  271,
      271,  370,  268,  369,  263,  263,  263,  263,  146,  368,
      269,  367,  146,  366,  263,  263,  263,  263,  263,  263,
      270,  365,  270,  364,  363,  271,  271,  271,  271,  146,

      362,   57,  361,  360,  146,  263,  263,  263,  263,  263,
      263,  141,  307,  307,  307,  307,  309,  309,  309,  309,
      265,  265,  265,  265,  212,  212,  212,  212,  359,  358,
      265,  265,  265,  265,  265,  265,  357,  356,  355,  149,
      354,  353,  352,  149,  351,  350,  349,   63,  348,  347,
      346,  265,  265,  265,  265,  265,  265,  345,  344,  343,
      149,  306,  342,  306,  341,  149,  307,  307,  307,  307,
      308,  336,  308,  335,  334,  309,  309,  309,  309,  271,
      271,  271,  271,  333,  332,  307,  307,  307,  307,  331,
      330,  329,  328,  327,  310,  326,  325,  324,  310,  323,

      337,  322,  321,  320,  337,  319,  318,  317,  309,  309,
      309,  309,  316,  315,  314,  310,  313,  312,  311,  311,
      310,  337,  305,  338,  304,  303,  337,  338,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  338,  286,  285,  284,  283,  338,
       55,  282,   55,   55,   55,   55,   55,   55,   55,   62,
      281,   62,  280,   62,   62,   62,   62,   62,   95,   95,
       95,   95,   55,   55,  279,   55,  278,  277,   55,   62,
       62,  276,   62,  275,  274,   62,  147,  261,  147,  147,
      147,  147,  147,  147,  147,  157,  157,  157,  206,  206,

      208,  208,  215,  215,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  235,  234,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  221,  214,  214,   96,  204,   96,  199,  198,
      193,  189,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,   63,  163,  162,  156,  144,  133,  132,
      129,  124,  123,  120,  109,  108,   98,   92,   87,   64,
       63,   54,  384,    3,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384
    } ;

static yyconst flex_int16_t yy_chk[771] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   10,   10,   11,
       16,  381,   19,   18,   19,   19,   19,   19,   40,   25,
       20,   40,   16,   18,   18,   20,   11,   22,   37,   22,

       22,   22,   22,   20,   25,   37,   25,   25,   27,   27,
       30,   37,   51,   22,   30,   38,    8,   21,   22,   21,
       21,   21,   21,   22,   38,   39,  380,   39,   62,   34,
       34,   34,   55,   21,   22,   34,   39,   34,   21,   34,
       22,   34,   34,   21,   21,   42,   45,   45,   22,   34,
      126,   47,   42,  379,   21,   47,   45,   57,   57,   45,
       21,   51,   56,   56,   62,   56,   47,  126,   21,   63,
       63,   21,   55,   80,   79,   71,   71,   71,   71,   79,
      378,  127,   96,   82,   75,   75,   75,   75,   84,   71,
       71,   85,  377,   84,   71,   80,  127,   56,   75,   75,

       82,  219,   56,   75,   79,   99,  131,   47,   82,   57,
       71,   71,   99,   85,  131,   86,   71,  122,   84,   75,
       75,   63,   96,  219,  122,   75,   76,   56,   76,   76,
       76,   76,   86,   77,  376,   77,   77,   77,   77,  152,
       86,   83,   76,   83,   83,   83,   83,   76,   78,   77,
       78,  158,   76,   78,   78,   78,   78,   83,  132,  138,
      132,  124,   83,   76,  152,  136,  136,   83,  136,   76,
       77,  124,  124,  139,  138,  264,  158,   76,   83,  142,
      150,  150,  150,  150,   83,  268,  139,  139,  142,  142,
      215,  145,   83,  145,  178,  178,  145,  145,  145,  145,

      136,  148,  157,  148,  262,  136,  148,  148,  148,  148,
      268,  264,  207,  139,  215,  142,  151,  151,  151,  151,
      205,  207,  207,  157,  217,  157,  216,  375,  157,  217,
      136,  151,  373,  205,  205,  151,  209,  209,  209,  209,
      211,  211,  211,  211,  262,  157,  312,  372,  207,  157,
      216,  370,  151,  157,  217,  220,  363,  151,  362,  312,
      205,  206,  361,  210,  210,  210,  210,  270,  270,  270,
      270,  360,  220,  355,  206,  206,  206,  206,  210,  354,
      220,  352,  210,  351,  206,  206,  206,  206,  206,  206,
      218,  349,  218,  348,  347,  218,  218,  218,  218,  210,

      346,  206,  345,  344,  210,  206,  206,  206,  206,  206,
      206,  208,  306,  306,  306,  306,  308,  308,  308,  308,
      208,  208,  208,  208,  212,  212,  212,  212,  343,  342,
      208,  208,  208,  208,  208,  208,  340,  339,  336,  212,
      335,  334,  327,  212,  326,  322,  321,  208,  320,  319,
      318,  208,  208,  208,  208,  208,  208,  317,  316,  315,
      212,  266,  314,  266,  313,  212,  266,  266,  266,  266,
      267,  304,  267,  303,  301,  267,  267,  267,  267,  271,
      271,  271,  271,  300,  299,  307,  307,  307,  307,  298,
      297,  296,  294,  293,  271,  292,  291,  289,  271,  288,

      307,  287,  286,  283,  307,  282,  281,  280,  309,  309,
      309,  309,  279,  278,  277,  271,  275,  274,  273,  272,
      271,  307,  261,  309,  260,  258,  307,  309,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  245,
      243,  242,  239,  238,  309,  237,  236,  233,  231,  309,
      385,  230,  385,  385,  385,  385,  385,  385,  385,  386,
      229,  386,  228,  386,  386,  386,  386,  386,  387,  387,
      387,  387,  388,  388,  227,  388,  226,  225,  388,  389,
      389,  224,  389,  223,  222,  389,  390,  204,  390,  390,
      390,  390,  390,  390,  390,  391,  391,  391,  392,  392,

      393,  393,  394,  394,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  187,
      186,  184,  183,  182,  181,  180,  179,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  161,  160,  155,  154,  137,  133,  130,  129,  128,
      125,  123,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   97,   94,   90,   81,   70,   49,   48,
       46,   44,   43,   41,   36,   35,   33,   26,   23,   15,
       12,    7,    3,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c-grammar.l"
#line 26 "c-grammar.l"
    //'
#include <stdio.h>
#include <stdbool.h>
#include "c-grammar.tab.h"

extern int yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */

#define sym_type(identifier) IDENTIFIER /* with no symbol table, fake it */

static void comment(void);
static int check_type(void);
static void analyzeDirective(void);
    
extern FILE* yyin;
extern FILE* yyout;

bool codeExpanderInsertedOnLine = false;
bool noBracketsCondition = true;
bool onNoBracketsCondition = false;
#line 780 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 49 "c-grammar.l"


#line 970 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 385 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 694 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "c-grammar.l"
{ analyzeDirective();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "c-grammar.l"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "c-grammar.l"
{ fprintf(yyout, "<comment>%s</comment>", yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>auto</keyword>");return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>break</keyword>");return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>case</keyword>");return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>char</type>");return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>const</keyword>");return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>continue</keyword>");return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>default</keyword>");return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>do</keyword>");return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>double</type>");return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>else</keyword>");return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>enum</keyword>");return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>extern</keyword>");return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>float</type>");return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>for</keyword>");return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>goto</keyword>");return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>if</keyword>");return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>inline</keyword>");return(INLINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>int</type>");return(INT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>long</type>");return(LONG); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>register</keyword>");return(REGISTER); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>restrict</keyword>");return(RESTRICT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>return</keyword>");return(RETURN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>short</type>");return(SHORT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>signed</type>");return(SIGNED); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>sizeof</keyword>");return(SIZEOF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>static</keyword>");return(STATIC); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>struct</keyword>");return(STRUCT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>switch</keyword>");return(SWITCH); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>typedef</keyword>");return(TYPEDEF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>union</keyword>");return(UNION); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>unsigned</type>");return(UNSIGNED); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "c-grammar.l"
{ fprintf(yyout, "%s", "<type>void</type>");return(VOID); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>volatile</keyword>");return(VOLATILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "c-grammar.l"
{ fprintf(yyout, "%s", "<keyword>while</keyword>");return(WHILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "c-grammar.l"
{ return ALIGNAS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "c-grammar.l"
{ return ALIGNOF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "c-grammar.l"
{ return ATOMIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "c-grammar.l"
{ return BOOL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "c-grammar.l"
{ return COMPLEX; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "c-grammar.l"
{ return GENERIC; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "c-grammar.l"
{ return IMAGINARY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "c-grammar.l"
{ return NORETURN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "c-grammar.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "c-grammar.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "c-grammar.l"
{ return FUNC_NAME; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "c-grammar.l"
{ fprintf(yyout, "<identifier>%s</identifier>", yytext);return check_type(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return I_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 105 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return I_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 106 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return I_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 109 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 110 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 111 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 112 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 113 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 114 "c-grammar.l"
{ fprintf(yyout, "<value>%s</value>", yytext);return F_CONSTANT; }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 116 "c-grammar.l"
{ fprintf(yyout, "<string>%s</string>", yytext); return STRING_LITERAL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ELLIPSIS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 "c-grammar.l"
{ fprintf(yyout, "%s", "&gt&gt=");return RIGHT_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 120 "c-grammar.l"
{ fprintf(yyout, "%s", "&lt&lt=");return LEFT_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 121 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ADD_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 122 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return SUB_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 123 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return MUL_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 124 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return DIV_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 125 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return MOD_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 126 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return AND_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return XOR_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 128 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return OR_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 129 "c-grammar.l"
{ fprintf(yyout, "%s", "&gt&gt");return RIGHT_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "c-grammar.l"
{ fprintf(yyout, "%s", "&lt&lt");return LEFT_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 131 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return INC_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 132 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return DEC_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 133 "c-grammar.l"
{ fprintf(yyout, "%s", "-&gt");return PTR_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 134 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return AND_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 135 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return OR_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 136 "c-grammar.l"
{ fprintf(yyout, "%s", "&lt=");return LE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 137 "c-grammar.l"
{ fprintf(yyout, "%s", "&gt=");return GE_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 138 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return EQ_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 139 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return NE_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 140 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ';'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 141 "c-grammar.l"
{ fprintf(yyout, "%s{%s", "<img class=\"code-expander\" src=\"img/collapse.png\">", "<div class=\"block\">"); return '{';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 142 "c-grammar.l"
{ fprintf(yyout, "</div>}");return '}'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 143 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ','; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 144 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ':'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 145 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '='; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '('; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 147 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ')'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 148 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '['; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return ']'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 150 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '.'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 151 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '&'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 152 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '!'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 153 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '~'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 154 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '-'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 155 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '+'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 156 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '*'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 157 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '/'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 158 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '%'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 159 "c-grammar.l"
{ fprintf(yyout, "%s", "&lt;");return '<'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 160 "c-grammar.l"
{ fprintf(yyout, "%s", "&gt;");return '>'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 161 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '^'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 162 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '|'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 163 "c-grammar.l"
{ fprintf(yyout, "%s", yytext);return '?'; }
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 164 "c-grammar.l"
{ fprintf(yyout, "<br>");}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 167 "c-grammar.l"
{ fprintf(yyout, " ");}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 168 "c-grammar.l"
{ /* discard bad characters */ }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 170 "c-grammar.l"
ECHO;
	YY_BREAK
#line 1606 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 385 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 385 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 384);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 170 "c-grammar.l"



int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

void analyzeDirective(void)
{
    fprintf(yyout, "<directive>#");

    int c;

    while ((c = input()) != '\n')
    {
        if (c == '<')
            fprintf(yyout, "&lt;");

        else if (c == '>')
            fprintf(yyout, "&gt;");
        else
            fprintf(yyout, "%c", c);
    }

    fprintf(yyout, "</directive><br>");

}

static void comment(void)
{
    fprintf(yyout, "<comment>/*");
    int c;

    while ((c = input()) != 0)
    {
        if (c == '*')
        {
            while ((c = input()) == '*')
                fprintf(yyout, "%c", c);

            if (c == '/')
            {
                fprintf(yyout, "*/</comment>");

                return;
            }

            if (c == 0)
                break;
        }

        else if (c == '<')
            fprintf(yyout, "&lt;");

        else if (c == '>')
            fprintf(yyout, "&gt;");

        else if (c == '\n')
            fprintf(yyout, "<br>");

        else
            fprintf(yyout, "%c", c);
    }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME:                /* previously defined */
        return TYPEDEF_NAME;
    case ENUMERATION_CONSTANT:        /* previously defined */
        return ENUMERATION_CONSTANT;
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}


